// Who owns the media this app ships, and whether we are allowed to ship it (issue #35).
//
// THE GAP THIS FILLS. The repo already records rights twice, and well: books carry `Module.rights`
// (issue #34, shown on About the Sources), and each place photograph carries `credit` + `licence` +
// `source` in places.ts — "credit is a licence obligation, not a courtesy". Everything else — the
// whole soundtrack, the three films, the poems, the anthem, the animal sounds, every photograph of a
// real person — shipped with no licence recorded anywhere.
//
// ATTRIBUTION IS NOT A LICENCE. Several of these assets ARE credited: `audioBy: "Jessica Mbangeni"`,
// `anthemBy: "Stellenbosch University Choir"`, a footer card linking the African Tribe Echoes
// channel. Someone thought carefully about naming people. But naming a performer does not grant the
// right to bundle their performance, and a YouTube credit is not a YouTube licence — the terms do
// not permit redistribution. Crediting and clearing are two different obligations; this file is the
// second one.
//
// WHY IT IS KEYED ON SOURCE WORKS, NOT FILES. 231 audio and video files come from about a dozen
// works: one track sliced into 202 clips, three films, three poems, one anthem, 22 animal sounds.
// One row per file would be 573 rows of mostly-duplicated truth, and a rights question is asked of a
// work, not of a byte range. Each entry claims the files it produced; `media-rights.test.ts` walks
// app/assets and fails if any file is claimed by nobody, or if a claimed count drifts.
//
// THE DECISION (2026-09-27, Tumo): unverified media KEEPS PLAYING while permission is requested,
// rather than being switched off first. The soundtrack is the app's ambience, and silencing it
// before anyone has said no is a large, certain loss against a risk nobody has measured. What
// changes today is that the repo can state exactly what it ships and on what basis — the requests
// are drafted in docs/16-media-rights-register.md and are Tumo's to send. `unverified` here means
// "we do not know that we may use this". It is a debt, not a clearance.
//
// Pure data — no require(), so it loads under `node --test` (the SP-032 trap that keeps provinces.ts
// un-importable). Components resolve the real assets; this file only names paths.

export type MediaRightsStatus =
  /** Someone has the right to ship it: public domain, an explicit licence, or our own work. */
  | "cleared"
  /** Machine-generated by this project (Pollinations, Gemini, ElevenLabs). Not a third party's work,
   *  so there is no licence to obtain — but it must be labelled in-app as an interpretation, never
   *  as evidence, which is its own obligation (AGENTS.md §4). */
  | "generated"
  /** We do not know that we may use it. The honest default, and a debt. */
  | "unverified"
  /** We know we may NOT use it, and it is still here. Nothing is in this state today; it exists so
   *  that a refusal has somewhere to be recorded that is louder than `unverified`. */
  | "must-replace";

export type MediaSource = {
  /** Stable slug. */
  id: string;
  /** The work, as its maker would name it. */
  title: string;
  /** Who owns it. "[NEEDS SOURCE]" when the repo does not record it — never a guess. */
  holder: string;
  /** Where it came from, checkable where possible. */
  origin: string;
  status: MediaRightsStatus;
  /** Why that status — the reasoning, so a reader can disagree with it. */
  basis: string;
  /**
   * What actually clears it: a licence name and URL, a public-domain calculation, or a reference to
   * the written permission. REQUIRED when `status` is "cleared", and the test enforces that.
   *
   * It is a separate field rather than a sentence in `basis` because prose cannot be checked. The
   * first version of this guard searched `basis` for the word "permission" — which the soundtrack's
   * own text already contains, in the sentence "Permission not yet requested". A row could be
   * flipped to "cleared" and the test would still pass. Evidence has to be a thing you either have
   * or do not.
   */
  evidence?: string;
  /** What must be shown to a reader, when something must. */
  attribution?: string;
  /** Paths under app/assets/ that this work produced. Three shapes, none of which reach into a
   *  subdirectory — a nested folder belongs to whoever names it, so nothing is covered by accident:
   *
   *    "flags/"           every file directly in flags/
   *    "journey/*.webp"   only the .webp directly in journey/ — the films there are somebody else's
   *    "audio/youth.mp3"  that one file
   *
   *  The middle shape exists because assets/journey/ holds both AI interpretations and three
   *  third-party films. One directory, two completely different rights answers. */
  paths: string[];
  /** How many files those paths cover. Pinned so that adding a 203rd clip is a failing test rather
   *  than a silent extension of somebody else's permission. */
  count: number;
};

export const mediaSources: MediaSource[] = [
  // ── Audio and video: the exposed group ───────────────────────────────────────────────────────
  {
    id: "soundtrack-african-tribe-echoes",
    title: "The Sound of Ancient Africa",
    holder: "African Tribe Echoes (YouTube channel)",
    origin: "https://www.youtube.com/@AfricanTribeEchoes",
    status: "unverified",
    basis:
      "Downloaded from YouTube as design/The-Sound-of-Ancient-Africa-Powerful.mp3 and cut into 202 " +
      "overlapping 45-second clips by design/make_clips.sh. The channel is credited in the site " +
      "footer, which is courtesy, not permission: YouTube's terms do not allow redistribution. This " +
      "is the most-used asset in the app — it plays across the whole journey — so it is also the " +
      "most exposed. Permission not yet requested; draft in docs/16.",
    attribution: "Music: African Tribe Echoes",
    paths: ["journey/clips/"],
    count: 202,
  },
  {
    id: "film-1652-they-came-with-chains",
    title: "They Came With Chains",
    holder: "[NEEDS SOURCE] — not recorded in this repo",
    origin:
      "design/1652-2026/They-Came-With-Chains_Media_ejo2cumV550_001_1080p.mp4 — the filename carries " +
      "an 11-character YouTube id (ejo2cumV550) and a downloader's _001_1080p suffix",
    status: "unverified",
    basis:
      "journey-media.ts describes the films as 'real archival/documentary media the user supplies', " +
      "but no supplier, licence or archive is recorded for this one. The filename is the only " +
      "provenance the repo holds, and it points at a download rather than a grant.",
    paths: ["journey/1652.mp4"],
    count: 1,
  },
  {
    id: "film-1816-we-are-growing",
    title: "We Are Growing",
    holder: "[NEEDS SOURCE] — not recorded in this repo",
    origin: "[NEEDS SOURCE] — no matching source file in design/",
    status: "unverified",
    basis:
      "Plays as part of the 1816 dot-story. Nothing in the repo records where it came from. A film " +
      "of this title is widely associated with a commercially owned South African recording, which " +
      "would put it firmly in copyright — but this repo cannot show that either way, so the honest " +
      "statement is that the source is unknown and must be established before it can be cleared.",
    paths: ["journey/1816-we-are-growing.mp4"],
    count: 1,
  },
  {
    id: "film-1816-song-of-kings",
    title: "The Song of Kings",
    holder: "[NEEDS SOURCE] — not recorded in this repo",
    origin:
      "[NEEDS SOURCE] — design/'Shaka Zulu - Epic African Music (The song of Kings).mp3' is a " +
      "name-alike in the same folder, but it is audio and this is video, so the link is unconfirmed",
    status: "unverified",
    basis:
      "Plays second in the 1816 dot-story. The footer credits a second music channel, Baobab Roots " +
      "Collective, and no asset in this register is yet traced to it — that credit and this film may " +
      "be related. Recorded as a question rather than as an answer.",
    paths: ["journey/1816-song-of-kings.mp4"],
    count: 1,
  },
  {
    id: "journey-walk-clip",
    title: "Walking animation (journey/walk.webm)",
    holder: "[NEEDS SOURCE] — not recorded in this repo",
    origin: "[NEEDS SOURCE] — no matching source file in design/",
    status: "unverified",
    basis:
      "The only .webm in the bundle. Nothing records whether it was generated for this app or taken " +
      "from somewhere, and the difference decides whether there is anything to clear. Listed rather " +
      "than assumed into the generated pile, because assuming is how a rights register becomes " +
      "worthless.",
    paths: ["journey/walk.webm"],
    count: 1,
  },
  {
    id: "poems-jessica-mbangeni",
    title: "Praise poems (Mandela; Women's Month)",
    holder: "Jessica Mbangeni",
    origin:
      "design/poems/'Jessica Mbangeni - Praise Poet_mandela.mp3' and " +
      "'Jessica Mbangeni Women's Month_poem.mp3'",
    status: "unverified",
    basis:
      "A living South African imbongi. Her Women's Day performance is credited in-app (`audioBy` in " +
      "national-days.ts); the Mandela recording is used on the Presidents screen with no credit " +
      "field at all, from the same batch of downloads. No permission is recorded for either. This " +
      "is the item that sits worst with the project's own purpose: an app about reclaiming African " +
      "voices should not be the one using an African artist's voice without asking.",
    attribution: "Performed by Jessica Mbangeni",
    paths: ["audio/mandela-praise-poem.mp3", "audio/womens-day-poem.mp3"],
    count: 2,
  },
  {
    id: "poem-sekhutlwana-sa-bannye",
    title: "Youth Day poem",
    holder: "Sekhutlwana sa Bannye",
    origin: "design/poems/'Sekhutlwana sa Bannye - African child day_Poem_june16.mp3'",
    status: "unverified",
    basis: "Credited in-app via `audioBy` in national-days.ts. No permission recorded.",
    attribution: "Performed by Sekhutlwana sa Bannye",
    paths: ["audio/youth-day-poem.mp3"],
    count: 1,
  },
  {
    id: "anthem-stellenbosch-choir",
    title: "National Anthem of South Africa — Stellenbosch University Choir",
    holder: "Stellenbosch University Choir (the recording)",
    origin:
      "design/South African Choir/'South African National Anthem  Stellenbosch University Choir.mp3'",
    status: "unverified",
    basis:
      "Two rights sit on top of each other here, and only one of them is easy. The WORDS AND TUNE " +
      "are old: Enoch Sontonga wrote Nkosi Sikelel' iAfrika in 1897 and died in 1905, so his part " +
      "is long in the public domain under the Copyright Act 98 of 1978 (life + 50). The RECORDING " +
      "is not — a performance carries its own copyright, held by the performers, whatever the age " +
      "of the song. Credited in-app via `anthemBy`; no permission recorded.",
    attribution: "Stellenbosch University Choir",
    paths: ["anthems/south-africa.mp3"],
    count: 1,
  },
  {
    id: "animal-sounds-curated",
    title: "Curated animal sounds",
    holder: "[NEEDS SOURCE] — various, not recorded",
    origin: "design/Animals sounds/ — 21 files with names like 'Lion Roar Sound Effect.mp3'",
    status: "unverified",
    basis:
      "Imported and re-encoded by scripts/import-animal-sounds.mjs. The names read like free " +
      "sound-library or video-site downloads, but no library, licence or URL is recorded for any of " +
      "them. Animals with no curated file keep an ElevenLabs-generated sound instead, so this " +
      "directory mixes third-party recordings with generated ones and the repo does not say which " +
      "is which — establishing that is part of clearing this row.",
    paths: ["animals/sounds/"],
    count: 22,
  },

  // ── Images ───────────────────────────────────────────────────────────────────────────────────
  {
    id: "hero-photographs",
    title: "Photographs of Sobukwe, Ngoyi, Biko and Madikizela-Mandela",
    holder: "[NEEDS SOURCE] — not recorded in this repo",
    origin: "[NEEDS SOURCE] — no sources.txt exists in any hero folder",
    status: "unverified",
    basis:
      "assets/heroes/README.md sets the rule itself: 'real, rights-cleared photographs — " +
      "public-domain, Creative-Commons, or otherwise licensed. Note the source (a sources.txt in " +
      "the folder is ideal).' No sources.txt was ever written, for any of the four. " +
      "HeroesScreens.tsx already tells the reader 'full credits to be confirmed', so the app is " +
      "honest about the gap while still showing the photographs. These are real people, three of " +
      "whom died within living memory, so the usual archive questions apply on top of copyright.",
    paths: ["heroes/biko/", "heroes/ngoyi/", "heroes/sobukwe/", "heroes/winnie/"],
    count: 49,
  },
  {
    id: "place-photographs",
    title: "Licensed photographs of the heritage places",
    holder: "Per photograph — recorded individually in content/places.ts",
    origin: "Wikimedia Commons and similar; each entry carries its own source URL",
    status: "cleared",
    basis:
      "Phase 7 (TOUR-05b) did this properly: every `Place.image` carries `credit`, `licence` (e.g. " +
      "'CC BY-SA 4.0') and a `source` URL, and PlaceScreen renders the credit because the licence " +
      "requires it. Not restated here — places.ts is the record, and duplicating it would create a " +
      "second truth to keep in step.",
    evidence:
      "Per-photograph `licence` + `source` URL on every `Place.image` in content/places.ts, e.g. " +
      "Robben Island: CC BY-SA 4.0, Moheen Reeyad, Wikimedia Commons.",
    attribution: "Rendered per photograph by PlaceScreen, from places.ts",
    paths: ["places/photos/"],
    count: 28,
  },
  {
    id: "ai-interpretations",
    title: "AI-generated scene, province, food, animal and day images",
    holder: "This project",
    origin:
      "Pollinations.ai and pre-rendered Gemini images; see docs/03 and the pollinations-visuals skill",
    status: "generated",
    basis:
      "Machine-generated for this app, so no third party's permission is at stake. The obligation is " +
      "a different one, and it is already met: each is labelled in-app as an interpretation rather " +
      "than as evidence (`imageIsAI` in journey-media.ts, the interpretation tag on national days), " +
      "and no AI image is used for a real person's face or a real identifiable place — which is " +
      "exactly why places carry licensed photographs instead.",
    attribution: "Labelled in-app as an AI interpretation",
    paths: ["animals/*.webp", "days/*.webp", "generated/*.webp", "journey/*.webp", "places/*.webp"],
    count: 191,
  },
  {
    id: "flags-flagcdn",
    title: "Flags of 54 African nations",
    holder: "Public domain",
    origin: "https://flagcdn.com",
    status: "cleared",
    basis:
      "content/anthems.ts records the provenance at the point of use: 'public-domain PNGs from " +
      "flagcdn.com'. National flags are not copyrightable in the ordinary way, and flagcdn " +
      "publishes them as public domain.",
    evidence: "flagcdn.com publishes the flag images as public domain; recorded at the point of use in content/anthems.ts.",
    paths: ["flags/"],
    count: 54,
  },
  {
    id: "brand-marks",
    title: "Third-party logos (UNISA, Botlhale AI, Solana, African Tribe Echoes, Baobab Roots)",
    holder: "Each mark's owner",
    origin: "assets/brand/",
    status: "unverified",
    basis:
      "These are other organisations' trademarks, shown on our footer. A logo raises a different " +
      "question from a licence — not 'may we copy it' but 'may we imply this relationship' — and " +
      "issue #55 already flags the partnership wording with UNISA and Botlhale as unverified. " +
      "Registered here so the assets are not mistaken for ours; the claim itself belongs to #55.",
    paths: ["brand/"],
    count: 7,
  },
  {
    id: "app-identity",
    title: "App icons, splash and favicon",
    holder: "This project",
    origin: "assets/ (root)",
    status: "cleared",
    basis: "Made for this app. No third-party rights.",
    evidence: "Original work of this project — nothing third-party was used to produce them.",
    paths: [
      "android-icon-background.png",
      "android-icon-foreground.png",
      "android-icon-monochrome.png",
      "favicon.png",
      "icon.png",
      "splash-icon.png",
    ],
    count: 6,
  },
];

/** Sources still carrying a rights debt — what docs/16 has to chase. */
export function unclearedSources(): MediaSource[] {
  return mediaSources.filter((s) => s.status === "unverified" || s.status === "must-replace");
}

/** Does this source claim `file` (a path relative to app/assets/, with "/" separators)?
 *
 *  Neither a directory nor an extension claim reaches into a subdirectory: `journey/` does not
 *  silently swallow `journey/clips/`, which belongs to somebody else entirely. That is the whole
 *  point — a permission granted for one work must not quietly extend to the next file dropped
 *  nearby. `media-rights.test.ts` proves it by walking the real tree. */
export function sourceClaims(source: MediaSource, file: string): boolean {
  return source.paths.some((p) => {
    if (p.endsWith("/")) return file.startsWith(p) && !file.slice(p.length).includes("/");
    const star = p.indexOf("/*.");
    if (star !== -1) {
      const dir = p.slice(0, star + 1);
      const ext = p.slice(star + 2);
      return file.startsWith(dir) && !file.slice(dir.length).includes("/") && file.endsWith(ext);
    }
    return file === p;
  });
}
