// MACHINE-DRAFT translations of the Sixteen June story, for the book reading and its narration
// (SP-115). Written by Claude in a session on 2026-09-24, the same way the literary modules' drafts
// in `drafts.data.ts` were — and with the same status: UNREVIEWED. The book shows each one labelled
// as a draft, and narration reads it in the language it is in. None of this is authoritative.
//
// TRANSLATION ONLY. Every sentence here restates its English source in `stories.ts` and adds
// nothing (AGENTS.md §2, T4). People, places, organisations, dates and numbers are kept verbatim —
// `story-drafts.test.ts` fails if a draft drops a name or a year its English source carries.
//
// CONFIDENCE IS NOT EVEN. Afrikaans, isiZulu, isiXhosa and Setswana drafts are likely closest; the
// siSwati, Xitsonga, Tshivenda and isiNdebele drafts are the likeliest to carry errors of idiom or
// word choice, and month names in those four use the loanword "Juni" rather than risk a wrong
// indigenous month. A speaker should review before any of this is treated as reviewed (see the
// story-draft review task in specs/tasks.md). `sources` is not translated: it is citations.

import type { LangCode } from "../i18n/languages";

export type StoryDraft = Partial<Record<LangCode, string>>;
export type StoryDraftPanel = { kicker: StoryDraft; headline: StoryDraft; body: StoryDraft };
export type StoryDrafts = { title: StoryDraft; standfirst: StoryDraft; panels: Record<string, StoryDraftPanel> };

export const STORY_DRAFTS: Record<string, StoryDrafts> = {
  "soweto-16-june": {
    title: {
      af: "Sestien Junie",
      tn: "16 Seetebosigo",
      zu: "16 kuJuni",
      xh: "16 kaJuni",
      st: "16 Phupjane",
      nso: "16 Juni",
      ss: "16 Juni",
      ts: "16 Juni",
      ve: "16 Juni",
      nr: "16 Juni",
    },
    standfirst: {
      af: "Vier plekke in Soweto, een dag in 1976, en die deel van die rekord wat steeds reggestel word.",
      tn: "Mafelo a mane mo Soweto, letsatsi le le lengwe ka 1976, le karolo ya rekoto e e santseng e baakanngwa.",
      zu: "Izindawo ezine eSoweto, usuku olulodwa ngo-1976, nengxenye yomlando esalungiswa namanje.",
      xh: "Iindawo ezine eSoweto, usuku olunye ngo-1976, nenxalenye yembali esalungiswa nangoku.",
      st: "Dibaka tse nne Soweto, letsatsi le le leng ka 1976, le karolo ya rekoto e ntseng e lokiswa.",
      nso: "Mafelo a mane ka Soweto, letšatši le tee ka 1976, le karolo ya rekhoto yeo e sa lokišwago.",
      ss: "Tindzawo letine eSoweto, lilanga linye nga-1976, nencenye yemlandvo lesolo ilungiswa.",
      ts: "Tindhawu ta mune eSoweto, siku rin'we hi 1976, ni xiphemu xa rekhodo lexi ha ku lulamisiwaka.",
      ve: "Fhethu huṋa ngei Soweto, ḓuvha ḽithihi nga 1976, na tshipiḓa tsha rekhodo tshine tsha kha ḓi khwiniswa.",
      nr: "Iindawo ezine eSoweto, ilanga linye ngo-1976, nesiqephe somlando esisalungiswa namhlanje.",
    },
    panels: {
      "orlando-west": {
        kicker: {
          af: "Orlando West · Soweto", tn: "Orlando West · Soweto", zu: "Orlando West · Soweto", xh: "Orlando West · Soweto",
          st: "Orlando West · Soweto", nso: "Orlando West · Soweto", ss: "Orlando West · Soweto", ts: "Orlando West · Soweto",
          ve: "Orlando West · Soweto", nr: "Orlando West · Soweto",
        },
        headline: {
          af: "’n Straat met ’n digter se naam",
          tn: "Mmila o o nang le leina la mmoki",
          zu: "Umgwaqo onegama lembongi",
          xh: "Isitrato esinegama lembongi",
          st: "Seterata se nang le lebitso la seroki",
          nso: "Setarata seo se nago le leina la seroki",
          ss: "Umgwaco lonelibito lembongi",
          ts: "Xitarata lexi nga ni vito ra mutlhokovetsi",
          ve: "Bada ḽine ḽa vha na dzina ḽa mubvumbi wa zwirendo",
          nr: "Isitarada esinebizo lembongi",
        },
        body: {
          af: "Vilakazistraat is vernoem na Benedict Wallet Vilakazi — die Zoeloedigter, die eerste swart Suid-Afrikaner wat ’n PhD verwerf het, en die skrywer van Inkondlo kaZulu. Nelson Mandela het vanaf 1946 op nommer 8115 gewoon.",
          tn: "Mmila wa Vilakazi o reeletswe ka Benedict Wallet Vilakazi — mmoki wa Sezulu, Moaforika Borwa wa ntlha yo Montsho go bona PhD, le mokwadi wa Inkondlo kaZulu. Nelson Mandela o ne a nna kwa nomorong 8115 go tloga ka 1946.",
          zu: "Umgwaqo iVilakazi uqanjwe ngoBenedict Wallet Vilakazi — imbongi yesiZulu, owokuqala omnyama waseNingizimu Afrika ukuthola iPhD, nombhali we-Inkondlo kaZulu. UNelson Mandela wahlala enombolweni 8115 kusukela ngo-1946.",
          xh: "Isitrato iVilakazi sithiywe ngoBenedict Wallet Vilakazi — imbongi yesiZulu, owokuqala oNtsundu woMzantsi Afrika ukufumana iPhD, nombhali we-Inkondlo kaZulu. UNelson Mandela wahlala kwinombolo 8115 ukusukela ngo-1946.",
          st: "Seterata sa Vilakazi se rehelletswe ka Benedict Wallet Vilakazi — seroki sa Sezulu, Moafrika Borwa wa pele e Motsho ho fumana PhD, le mongodi wa Inkondlo kaZulu. Nelson Mandela o ile a dula nomorong ya 8115 ho tloha ka 1946.",
          nso: "Setarata sa Vilakazi se reeletšwe ka Benedict Wallet Vilakazi — seroki sa Sezulu, Moafrika-Borwa wa mathomo yo moso go hwetša PhD, le mongwadi wa Inkondlo kaZulu. Nelson Mandela o dutše nomorong ya 8115 go tloga ka 1946.",
          ss: "Umgwaco iVilakazi uetsiwe ngaBenedict Wallet Vilakazi — imbongi yesiZulu, wekucala lomnyama waseNingizimu Afrika kutfola iPhD, nembhali we-Inkondlo kaZulu. UNelson Mandela wahlala enombolweni 8115 kusukela nga-1946.",
          ts: "Xitarata xa Vilakazi xi thyiwe hi Benedict Wallet Vilakazi — mutlhokovetsi wa Xizulu, Muafrika-Dzonga wo sungula wa ntima ku kuma PhD, ni mutsari wa Inkondlo kaZulu. Nelson Mandela u tshame eka nomboro 8115 ku sukela hi 1946.",
          ve: "Bada ḽa Vilakazi ḽo ṱhewa nga dzina ḽa Benedict Wallet Vilakazi — mubvumbi wa zwirendo wa Tshizulu, Muafrika Tshipembe wa u thoma o swifhalaho u wana PhD, na muṅwali wa Inkondlo kaZulu. Nelson Mandela o dzula kha nomboro 8115 u bva nga 1946.",
          nr: "Isitarada iVilakazi sithiwe ngoBenedict Wallet Vilakazi — imbongi yesiZulu, owokuthoma omnyama weSewula Afrika ukuthola iPhD, nomtloli we-Inkondlo kaZulu. UNelson Mandela wahlala enomborweni 8115 ukuthoma ngo-1946.",
        },
      },
      "eight-one-one-five": {
        kicker: {
          af: "Vilakazistraat 8115",
          tn: "8115 Mmila wa Vilakazi",
          zu: "8115 Umgwaqo iVilakazi",
          xh: "8115 Isitrato iVilakazi",
          st: "8115 Seterata sa Vilakazi",
          nso: "8115 Setarata sa Vilakazi",
          ss: "8115 Umgwaco iVilakazi",
          ts: "8115 Xitarata xa Vilakazi",
          ve: "8115 Bada ḽa Vilakazi",
          nr: "8115 Isitarada iVilakazi",
        },
        headline: {
          af: "Vier kamers",
          tn: "Diphaposi di le nne",
          zu: "Amakamelo amane",
          xh: "Amagumbi amane",
          st: "Diphaposi tse nne",
          nso: "Dikamore tše nne",
          ss: "Emakamelo lamane",
          ts: "Tikamara ta mune",
          ve: "Dzirumu nṋa",
          nr: "Amakamelo amane",
        },
        body: {
          af: "Die huis op die hoek van Ngakanestraat. Hy het dit in 1997 aan die Soweto Heritage Trust gegee, en dit by sy vrylating as die middelpunt van sy wêreld beskryf.",
          tn: "Ntlo e e kwa sekhutlong sa mmila wa Ngakane. O e neetse Soweto Heritage Trust ka 1997, mme fa a gololwa a e tlhalosa e le bogare jwa lefatshe la gagwe.",
          zu: "Indlu esekhoneni likaNgakane Street. Wayinikela kuSoweto Heritage Trust ngo-1997, futhi lapho ekhululwa wayichaza njengesizinda somhlaba wakhe.",
          xh: "Indlu ekwikona yesitrato iNgakane. Wayinikela kwiSoweto Heritage Trust ngo-1997, kwaye xa wayekhululwa wayichaza njengombindi wehlabathi lakhe.",
          st: "Ntlo e hukung ya seterata sa Ngakane. O ile a e nehelana ho Soweto Heritage Trust ka 1997, mme ha a lokollwa a e hlalosa e le bohareng ba lefatshe la hae.",
          nso: "Ntlo yeo e lego sekhutlong sa setarata sa Ngakane. O e neetše Soweto Heritage Trust ka 1997, gomme ge a lokollwa a e hlaloša bjalo ka bogare bja lefase la gagwe.",
          ss: "Indlu lesekhoneni lemgwaco iNgakane. Wayinikela ku-Soweto Heritage Trust nga-1997, futsi nakakhululwa wayichaza njengemkhatsi wemhlaba wakhe.",
          ts: "Yindlu leyi nga ekhonweni ra xitarata xa Ngakane. U yi nyikile Soweto Heritage Trust hi 1997, naswona loko a ntshunxiwa u yi hlamusele tanihi xivindzi xa misava ya yena.",
          ve: "Nnḓu i re khoneni ya bada ḽa Ngakane. O i ṋea Soweto Heritage Trust nga 1997, nahone musi a tshi vhofhololwa o i ṱalutshedza sa vhukati ha shango ḽawe.",
          nr: "Indlu esekhoneni lesitarada iNgakane. Wayinikela ku-Soweto Heritage Trust ngo-1997, begodu nakakhululwa wayihlathulula njengephakathi lephasi lakhe.",
        },
      },
      "the-decree": {
        kicker: {
          af: "16 Junie 1976",
          tn: "16 Seetebosigo 1976",
          zu: "16 kuJuni 1976",
          xh: "16 kaJuni 1976",
          st: "16 Phupjane 1976",
          nso: "16 Juni 1976",
          ss: "16 Juni 1976",
          ts: "16 Juni 1976",
          ve: "16 Juni 1976",
          nr: "16 Juni 1976",
        },
        headline: {
          af: "Hulle het teen ’n taal opgeruk",
          tn: "Ba ne ba gwanta kgatlhanong le puo",
          zu: "Bamasha bephikisa ulimi",
          xh: "Bamatsha bechasa ulwimi",
          st: "Ba ile ba mausa kgahlanong le puo",
          nso: "Ba gwantše kgahlanong le polelo",
          ss: "Bamasha baphikisana nelulwimi",
          ts: "Va fambile va lwisana ni ririmi",
          ve: "Vho maswia vha tshi hanedza luambo",
          nr: "Bamatjha baphikisana nelimi",
        },
        body: {
          af: "Duisende skoolleerlinge in Soweto het opgeruk teen die dwang om in Afrikaans te leer. Die polisie het op die kinders losgebrand.",
          tn: "Diketekete tsa baithuti ba dikolo kwa Soweto ba ne ba gwanta kgatlhanong le go patelelwa go ithuta ka Seaforikanse. Mapodise a ne a thunya bana.",
          zu: "Izinkulungwane zabafundi bezikole zaseSoweto bamasha bephikisa ukuphoqwa ukuthi bafunde ngesiBhunu. Amaphoyisa adubula izingane.",
          xh: "Amawaka abafundi bezikolo zaseSoweto bamatsha bechasa ukunyanzelwa ukuba bafunde ngesiBhulu. Amapolisa adubula abantwana.",
          st: "Dikete tsa baithuti ba dikolo tsa Soweto di ile tsa mausa kgahlanong le ho qobellwa ho ithuta ka Seburu. Mapolesa a ile a thunya bana.",
          nso: "Dikete tša barutwana ba dikolo tša Soweto ba gwantše kgahlanong le go gapeletšwa go ithuta ka Seburu. Maphodisa a thuntšhitše bana.",
          ss: "Tinkhulungwane tebafundzi betikolwa taseSoweto bamasha baphikisana nekuphoceleleka kufundza ngesiBhunu. Emaphoyisa adubula bantfwana.",
          ts: "Magidi ya swichudeni swa swikolo swa Soweto va fambile va lwisana ni ku sindzisiwa ku dyondza hi Xibunu. Maphorisa ma dubule vana.",
          ve: "Zwigidi zwa matshudeni a zwikolo zwa Soweto vho maswia vha tshi hanedza u kombetshedzwa u guda nga Tshibunu. Mapholisa a thuntsha vhana.",
          nr: "Iinkulungwana zabafundi bezikolo zeSoweto bamatjha baphikisana nokukatelelwa bona bafunde ngesiBhunu. Amapholisa athuda abantwana.",
        },
      },
      "the-memorial": {
        kicker: {
          af: "Orlando West", tn: "Orlando West", zu: "Orlando West", xh: "Orlando West", st: "Orlando West",
          nso: "Orlando West", ss: "Orlando West", ts: "Orlando West", ve: "Orlando West", nr: "Orlando West",
        },
        headline: {
          af: "Die museum staan waar hy geval het",
          tn: "Musiamo o eme fa a neng a wela teng",
          zu: "Imnyuziyamu imi lapho awela khona",
          xh: "Imyuziyam ime apho wawa khona",
          st: "Musiamo o eme moo a ileng a wela teng",
          nso: "Musiamo o eme moo a wetšego gona",
          ss: "Imnyuziyamu yeme lapho awela khona",
          ts: "Muziyamu wu yime laha a weleke kona",
          ve: "Miziamu yo ima hune a wela hone",
          nr: "Imnyuziyamu ijame lapho awela khona",
        },
        body: {
          af: "Dit gedenk die skoolkinders wat gedood is toe die polisie op die optog losgebrand het. Dit is op 16 Junie 2002 geopen, naby die plek waar Hector Pieterson geskiet is.",
          tn: "O gopola baithuti ba ba bolailweng fa mapodise a ne a thunya mogwanto. O butswe ka 16 Seetebosigo 2002, gaufi le felo fa Hector Pieterson a neng a thuntswe teng.",
          zu: "Ikhumbula izingane zesikole ezabulawa lapho amaphoyisa edubula imashi. Yavulwa ngomhla ziyi-16 kuJuni 2002, eduze nendawo lapho uHector Pieterson adutshulwa khona.",
          xh: "Ikhumbula abantwana besikolo ababulawa xa amapolisa adubula umngcelele. Yavulwa ngomhla we-16 kaJuni 2002, kufutshane nendawo apho uHector Pieterson wadutyulwa khona.",
          st: "O hopola bana ba sekolo ba bolailweng ha mapolesa a thunya mohwanto. O butswe ka la 16 Phupjane 2002, haufi le sebaka seo Hector Pieterson a ileng a thunngwa ho sona.",
          nso: "O gopola bana ba sekolo bao ba bolailwego ge maphodisa a thuntšha mogwanto. O butšwe ka la 16 Juni 2002, kgauswi le lefelo leo Hector Pieterson a thuntšhitšwego go lona.",
          ss: "Ikhumbula bantfwana besikolwa lababulawa ngesikhatsi emaphoyisa adubula imashi. Yavulwa mhla ti-16 Juni 2002, eduze nendzawo lapho Hector Pieterson adutjulwa khona.",
          ts: "Wu tsundzuka vana va xikolo lava dlayiweke loko maphorisa ma dubula nfambo. Wu pfuriwe hi 16 Juni 2002, kusuhi ni ndhawu leyi Hector Pieterson a dubuleriweke eka yona.",
          ve: "I humbula vhana vha tshikolo vhe vha vhulahwa musi mapholisa a tshi thuntsha maswia. Yo vulwa nga ḽa 16 Juni 2002, tsini na fhethu he Hector Pieterson a thuntshelwa hone.",
          nr: "Ikhumbula abantwana besikolo ababulawa lokha amapholisa nathuda imatjha. Yavulwa ngomhla ka-16 Juni 2002, eduze nendawo lapho uHector Pieterson athudwa khona.",
        },
      },
      "the-photograph": {
        kicker: {
          af: "Die foto",
          tn: "Setshwantsho",
          zu: "Isithombe",
          xh: "Ifoto",
          st: "Senepe",
          nso: "Seswantšho",
          ss: "Sitfombe",
          ts: "Xifaniso",
          ve: "Tshifanyiso",
          nr: "Isithombe",
        },
        headline: {
          af: "Agttien dra twaalf",
          tn: "Wa dingwaga di le 18 a tshotse wa di le 12",
          zu: "Oneminyaka engu-18 ethwele oneminyaka engu-12",
          xh: "Oneminyaka eli-18 ephethe oneminyaka eli-12",
          st: "Wa dilemo tse 18 a jere wa tse 12",
          nso: "Wa mengwaga ye 18 a rwele wa ye 12",
          ss: "Loneminyaka le-18 atfwele loneminyaka le-12",
          ts: "Wa malembe ya 18 a rhwele wa 12",
          ve: "Wa miṅwaha ya 18 o hwala wa 12",
          nr: "Oneminyaka eli-18 athwele oneli-12",
        },
        body: {
          af: "Sam Nzima het die agttienjarige Mbuyisa Makhubu afgeneem terwyl hy die dodelik gewonde twaalfjarige Hector Pieterson dra, met Antoinette Sithole wat langs hulle hardloop. Die foto het in die wêreld se koerante verskyn. Nzima het jare lank onder polisietoesig geleef, en Makhubu het in ’n ballingskap gevlug waaruit hy nooit teruggekeer het nie.",
          tn: "Sam Nzima o ne a tsaya setshwantsho sa Mbuyisa Makhubu wa dingwaga di le 18 a tshotse Hector Pieterson wa dingwaga di le 12 yo o gobaditsweng go ya losong, Antoinette Sithole a taboga fa thoko ga bone. Se ne sa gatisiwa mo dikgannyeng tsa lefatshe. Nzima o ne a tshela dingwaga a lebeletswe ke mapodise, mme Makhubu a tshabela botshabelong jo a iseng a boe go jone.",
          zu: "USam Nzima wathwebula uMbuyisa Makhubu oneminyaka engu-18 ethwele uHector Pieterson oneminyaka engu-12 owayelimele kabi eseduze nokufa, u-Antoinette Sithole egijima eceleni kwabo. Sashicilelwa emaphephandabeni omhlaba. UNzima waphila iminyaka eqashwe ngamaphoyisa, kanti uMakhubu wabalekela ekudingisweni angazange abuye kukho.",
          xh: "USam Nzima wafota uMbuyisa Makhubu oneminyaka eli-18 ephethe uHector Pieterson oneminyaka eli-12 owayenzakele kakhulu esiya ekufeni, uAntoinette Sithole ebaleka ecaleni kwabo. Yapapashwa kumaphephandaba ehlabathi. UNzima waphila iminyaka ebekwe esweni ngamapolisa, kwaye uMakhubu wabalekela elubhacweni angazange abuye kulo.",
          st: "Sam Nzima o ile a nka senepe sa Mbuyisa Makhubu wa dilemo tse 18 a jere Hector Pieterson wa dilemo tse 12 ya lemetseng ho isa lefung, Antoinette Sithole a matha haufi le bona. Se ile sa phatlalatswa dikoranteng tsa lefatshe. Nzima o ile a phela dilemo a ntse a hlokometswe ke mapolesa, mme Makhubu a balehela botlamuweng boo a sa kang a kgutla ho bona.",
          nso: "Sam Nzima o tšere seswantšho sa Mbuyisa Makhubu wa mengwaga ye 18 a rwele Hector Pieterson wa mengwaga ye 12 yo a gobetšego go iša lehung, Antoinette Sithole a kitima kgauswi le bona. Se gatišitšwe dikuranteng tša lefase. Nzima o phetše mengwaga a hlokometšwe ke maphodisa, gomme Makhubu a tšhabela bothopšing bjoo a sego a boa go bjona.",
          ss: "Sam Nzima watsatsa sitfombe saMbuyisa Makhubu loneminyaka le-18 atfwele Hector Pieterson loneminyaka le-12 lolimale kakhulu kwaze kwaba sekufeni, Antoinette Sithole agijima eceleni kwabo. Sashicilelwa emaphephandzabeni emhlaba. Nzima waphila iminyaka abukwa ngemaphoyisa, futsi Makhubu wabalekela ekudzingisweni langakaze abuye kuko.",
          ts: "Sam Nzima u tekile xifaniso xa Mbuyisa Makhubu wa malembe ya 18 a rhwele Hector Pieterson wa malembe ya 12 loyi a vavisekeke ku fikela eku feni, Antoinette Sithole a tsutsuma etlhelo ka vona. Xi humesiwile emaphepheni ya mahungu ya misava. Nzima u hanye malembe a languteriwa hi maphorisa, naswona Makhubu u balekele evuhlapfeni lebyi a nga tlhelangiki a vuya eka byona.",
          ve: "Sam Nzima o dzhia tshifanyiso tsha Mbuyisa Makhubu wa miṅwaha ya 18 o hwala Hector Pieterson wa miṅwaha ya 12 we a huvhala u swika lufuni, Antoinette Sithole a tshi gidima tsini navho. Tsho gandiswa kha ma-nyuspepa a shango. Nzima o tshila miṅwaha a tshi khou sedzuluswa nga mapholisa, nahone Makhubu o shavhela vhutshavhani he a si tsha vhuya a vhuya u bva khaho.",
          nr: "USam Nzima wathatha isithombe sakaMbuyisa Makhubu oneminyaka eli-18 athwele uHector Pieterson oneminyaka eli-12 owalimala kwaba kukufa, u-Antoinette Sithole agijima eceleni kwabo. Sagadangiswa emaphephandabeni wephasi. UNzima waphila iminyaka aqalwa ngamapholisa, begodu uMakhubu wabalekela ekudingisweni angazange abuye kikho.",
        },
      },
      "regina-mundi": {
        kicker: {
          af: "Rockville", tn: "Rockville", zu: "Rockville", xh: "Rockville", st: "Rockville",
          nso: "Rockville", ss: "Rockville", ts: "Rockville", ve: "Rockville", nr: "Rockville",
        },
        headline: {
          af: "Die volk se kerk",
          tn: "Kereke ya batho",
          zu: "Isonto labantu",
          xh: "Icawa yabantu",
          st: "Kereke ya setjhaba",
          nso: "Kereke ya batho",
          ss: "Libandla lebantfu",
          ts: "Kereke ya vanhu",
          ve: "Kereke ya vhathu",
          nr: "Isonto labantu",
        },
        body: {
          af: "Baie wat die skietery in Orlando West ontvlug het, het hierheen gekom, na die grootste Katolieke kerk in die land — een wat sy deure vir anti-apartheidsvergaderings oopgestel en aktiviste beskut het. Die polisie het hulle na binne gevolg en geskiet. Die merke is steeds daar.",
          tn: "Ba bantsi ba ba neng ba tshaba go thunya kwa Orlando West ba ne ba tla fa, kwa kerekeng e kgolo go gaisa ya Katoliki mo nageng — e e neng e buletse dikopano tse di kgatlhanong le tlhaolele dikgoro mme e sireletsa badiragatsi. Mapodise a ne a ba sala morago ka fa teng mme a thunya. Matshwao a santse a le teng.",
          zu: "Abaningi ababaleka ukudubula e-Orlando West beza lapha, esontweni elikhulu kunawo wonke lamaKhatholika ezweni — elalivulele imihlangano yokulwa nobandlululo iminyango futhi livikela izishoshovu. Amaphoyisa abalandela ngaphakathi adubula. Izimpawu zisekhona.",
          xh: "Abaninzi ababaleka ukudutyulwa e-Orlando West beza apha, kweyona cawa inkulu yamaKatolika elizweni — eyayivule iingcango zayo kwiintlanganiso ezichasene nocalucalulo kwaye ikhusela abalweli. Amapolisa abalandela ngaphakathi adubula. Imikhondo isekhona.",
          st: "Ba bangata ba ileng ba baleha ho thunngwa Orlando West ba ile ba tla mona, kerekeng e kgolo ka ho fetisisa ya Katolike naheng — e neng e butse mamati a yona dikopanong tse kgahlanong le kgethollo mme e sireletsa baitseki. Mapolesa a ile a ba latela kahare mme a thunya. Matshwao a ntse a le teng.",
          nso: "Ba bantši bao ba tšhabilego go thuntšha ka Orlando West ba tlile mo, kerekeng ye kgolo kudu ya Katoliki nageng — yeo e bego e bulela dikopano tša kgahlanong le kgethollo mejako gomme e šireletša bahlabani. Maphodisa a ba latetše ka gare gomme a thuntšha. Maswao a sa le gona.",
          ss: "Labanyenti lababaleka kudubula e-Orlando West beta lapha, esontweni lelikhulu kakhulu lemaKhatholika eveni — lebelivulele imihlangano yekulwa nebandlululo iminyango futsi livikela tishoshovu. Emaphoyisa abalandzela ngekhatsi adubula. Timphawu tisekhona.",
          ts: "Vo tala lava balekeke ku dubula eOrlando West va tile laha, ekerekeni leyikulu swinene ya Khatoliki etikweni — leyi a yi pfulele tinhlengeletano leti lwisanaka ni xihlawuhlawu tinyangwa naswona yi sirhelela valweri. Maphorisa ma va landzele endzeni ma dubula. Swikombiso swa ha ri kona.",
          ve: "Vhanzhi vhe vha shavha u thuntsha ngei Orlando West vho ḓa fhano, kha kereke khulwane kha dzoṱhe ya Khatholiki shangoni — ye ya vha yo vulela miṱangano ya u lwa na tshiṱalula mivhero yayo nahone i tshi tsireledza vhalwela-mbofholowo. Mapholisa a vha tevhela nga ngomu a thuntsha. Maswayo a kha ḓi vha hone.",
          nr: "Abanengi ababaleka ukuthudwa e-Orlando West beza lapha, esontweni elikhulu khulu lamaKhatholika enarheni — elaberilivulele imihlangano ephikisana nobandlululo iminyango begodu livikela izishoshovu. Amapholisa abalandela ngaphakathi athuda. Amatshwayo asese khona.",
        },
      },
      "who-is-missing": {
        kicker: {
          af: "Wat die rekord uitlaat",
          tn: "Se rekoto e se tlogelang",
          zu: "Lokho umlando okushiyayo",
          xh: "Oko imbali ekushiyayo",
          st: "Seo rekoto e se siileng",
          nso: "Seo rekhoto e se tlogelago",
          ss: "Loko umlandvo lokushiyako",
          ts: "Leswi rekhodo yi swi siyaka",
          ve: "Zwine rekhodo ya zwi sia",
          nr: "Lokho umlando okutjhiyako",
        },
        headline: {
          af: "Noem die vroue",
          tn: "Bitsang basadi ka maina",
          zu: "Yisho amagama abesifazane",
          xh: "Chaza amagama abasetyhini",
          st: "Bitsang basadi ka mabitso",
          nso: "Bitšang basadi ka maina",
          ss: "Bitani bomake ngemagama",
          ts: "Vitanani vavasati hi mavito",
          ve: "Ambani vhafumakadzi nga madzina",
          nr: "Bizani abomma ngamabizo",
        },
        body: {
          af: "Die historikus Thando Sipuye voer aan dat die dag onthou word deur ’n klein groep manlike studenteleiers, terwyl die vroue wat die optog gereël het, daarin opgeruk het, die studente daarna versteek en gevoed het, en self geskiet en aangehou is, aan die kant van die verhaal staan. Hy herwin name: Sibongile Mkhabela, die enigste vrou op die uitvoerende komitee van die Soweto Students' Representative Council. Winnie Motlalepula Kgware, die eerste president van die Black People's Convention. Hermina Leroke, op 17 Junie 1976 in Diepkloof geskiet.",
          tn: "Rahisitori Thando Sipuye o bolela gore letsatsi le gopolwa ka setlhopha se sennye sa baeteledipele ba baithuti ba banna, fa basadi ba ba rulagantseng mogwanto, ba gwantang mo go one, ba fitlhileng le go fepa baithuti morago, mme bone ka bobone ba thuntswe le go tshwarwa, ba le kwa dintlheng tsa pego. O busetsa maina: Sibongile Mkhabela, mosadi a le esi mo khuduthamaga ya Soweto Students' Representative Council. Winnie Motlalepula Kgware, moporesidente wa ntlha wa Black People's Convention. Hermina Leroke, yo o thuntsweng kwa Diepkloof ka 17 Seetebosigo 1976.",
          zu: "Isazi-mlando uThando Sipuye uthi lolu suku lukhunjulwa ngeqembu elincane labaholi babafundi besilisa, kanti abesifazane abahlela imashi, abamasha kuyo, abafihla futhi bondla abafundi ngemuva kwalokho, futhi nabo ngokwabo badutshulwa baboshwa, basemaphethelweni endaba. Ubuyisa amagama: uSibongile Mkhabela, okuwukuphela kowesifazane kwisigungu esiphezulu seSoweto Students' Representative Council. UWinnie Motlalepula Kgware, umongameli wokuqala weBlack People's Convention. UHermina Leroke, owadutshulwa eDiepkloof ngomhla ziyi-17 kuJuni 1976.",
          xh: "Umbhali-mbali uThando Sipuye uthi olu suku lukhunjulwa ngeqela elincinci leenkokeli zabafundi abangamadoda, ngelixa abasetyhini abaququzelela umngcelele, abamatsha kuwo, abafihla baza bondla abafundi emva koko, kwaye nabo ngokwabo badutyulwa bavalelwa, bebekwe ecaleni kwengxelo. Ubuyisa amagama: uSibongile Mkhabela, ekuphela kwebhinqa kwikomiti yolawulo yeSoweto Students' Representative Council. UWinnie Motlalepula Kgware, umongameli wokuqala weBlack People's Convention. UHermina Leroke, owadutyulwa eDiepkloof ngomhla we-17 kaJuni 1976.",
          st: "Rahistori Thando Sipuye o re letsatsi lena le hopolwa ka sehlopha se senyane sa baetapele ba baithuti ba banna, athe basadi ba hlophisitseng mohwanto, ba mausang ho wona, ba patileng le ho fepa baithuti kamora moo, mme bona ka bobona ba thunngwa le ho tshwarwa, ba behilwe mahlakoreng a tlaleho. O kgutlisa mabitso: Sibongile Mkhabela, mosadi a le mong feela komiting e phahameng ya Soweto Students' Representative Council. Winnie Motlalepula Kgware, mopresidente wa pele wa Black People's Convention. Hermina Leroke, ya thunngweng Diepkloof ka la 17 Phupjane 1976.",
          nso: "Rahistori Thando Sipuye o re letšatši le le gopolwa ka sehlopha se se nyane sa baetapele ba barutwana ba banna, mola basadi bao ba rulagantšego mogwanto, ba gwantšego go wona, ba utilego le go fepa barutwana ka morago, gomme bona ka bobona ba thuntšhitšwe le go swarwa, ba le mathokong a pego. O bušetša maina: Sibongile Mkhabela, mosadi a nnoši komiting ya phethagatšo ya Soweto Students' Representative Council. Winnie Motlalepula Kgware, mopresidente wa mathomo wa Black People's Convention. Hermina Leroke, yo a thuntšhitšwego Diepkloof ka la 17 Juni 1976.",
          ss: "Sati semlandvo Thando Sipuye utsi lelilanga likhunjulwa ngelicembu lelincane lebaholi bebafundzi labadvuna, kantsi bomake labahlela imashi, labamasha kuyo, labafihla futsi bondla bafundzi ngemuva kwaloko, futsi nabo ngekwabo badutjulwa baboshwa, basemaceleni endzaba. Ubuyisa emagama: Sibongile Mkhabela, kuphela kwemfati kulikomidi lelibusako le-Soweto Students' Representative Council. Winnie Motlalepula Kgware, umengameli wekucala we-Black People's Convention. Hermina Leroke, lowadutjulwa eDiepkloof mhla ti-17 Juni 1976.",
          ts: "N'wamatimu Thando Sipuye u vula leswaku siku leri ri tsundzukiwa hi ntlawa lowutsongo wa varhangeri va swichudeni va xinuna, kasi vavasati lava lunghiseleleke nfambo, lava fambeke eka wona, lava tumbeteke ni ku phamela swichudeni endzhaku, naswona vona hi voxe va duburiwile va khotsiwa, va le matlhelweni ya mhaka. U vuyisa mavito: Sibongile Mkhabela, wansati ntsena eka komiti ya vulawuri ya Soweto Students' Representative Council. Winnie Motlalepula Kgware, presidente wo sungula wa Black People's Convention. Hermina Leroke, loyi a duburiweke eDiepkloof hi 17 Juni 1976.",
          ve: "Muḓivhi wa ḓivhazwakale Thando Sipuye u amba uri ḓuvha iḽi ḽi humbulwa nga tshigwada tshiṱuku tsha vharangaphanḓa vha matshudeni vha vhanna, ngeno vhafumakadzi vhe vha dzudzanya maswia, vhe vha maswia khao, vhe vha dzumba na u ḽisa matshudeni nga murahu, nahone vhone vhaṋe vha thuntshwa vha farwa, vha kha mahalwa a nyambo. U vhuedzedza madzina: Sibongile Mkhabela, mufumakadzi e eṱhe kha komiti ya vhulangi ya Soweto Students' Representative Council. Winnie Motlalepula Kgware, phresidennde wa u thoma wa Black People's Convention. Hermina Leroke, we a thuntshwa ngei Diepkloof nga ḽa 17 Juni 1976.",
          nr: "Isazi somlando uThando Sipuye uthi ilanga leli likhunjulwa ngesiqhema esincani sabadosiphambili babafundi abadoda, kanti abomma abahlela imatjha, abamatjha kiyo, abafihla begodu bondla abafundi ngemva kwalokho, begodu nabo ngokwabo bathudwa babotjhwa, bangasemaphethelweni wendaba. Ubuyisa amabizo: uSibongile Mkhabela, kwaphela umma ekomitini elawulako le-Soweto Students' Representative Council. UWinnie Motlalepula Kgware, umongameli wokuthoma we-Black People's Convention. UHermina Leroke, owathudwa eDiepkloof ngomhla ka-17 Juni 1976.",
        },
      },
      antoinette: {
        kicker: {
          af: "In die foto",
          tn: "Mo setshwantshong",
          zu: "Esithombeni",
          xh: "Kwifoto",
          st: "Senepeng",
          nso: "Seswantšhong",
          ss: "Esitfombeni",
          ts: "Eka xifaniso",
          ve: "Kha tshifanyiso",
          nr: "Esithombeni",
        },
        headline: {
          af: "Antoinette Sithole het ook opgeruk",
          tn: "Antoinette Sithole le ene o ne a gwanta",
          zu: "U-Antoinette Sithole naye wayemasha",
          xh: "UAntoinette Sithole naye wayematsha",
          st: "Antoinette Sithole le yena o ne a mausa",
          nso: "Antoinette Sithole le yena o be a gwanta",
          ss: "Antoinette Sithole naye bekamasha",
          ts: "Antoinette Sithole na yena a a famba",
          ve: "Antoinette Sithole na ene o vha a tshi khou maswia",
          nr: "U-Antoinette Sithole naye bekamatjha",
        },
        body: {
          af: "Sy word onthou as Hector se suster. Sipuye se punt is dat sy in eie reg ’n betoger was, en dat die mees gereproduseerde beeld van die dag dieselfde gewoonte van vergeet dra as die res van die rekord.",
          tn: "O gopolwa e le kgaitsadie wa ga Hector. Ntlha ya ga Sipuye ke gore e ne e le mogwanti ka boene, le gore setshwantsho se se gatisitsweng thata sa letsatsi leo se rwele mokgwa o o tshwanang wa go lebala jaaka rekoto yotlhe.",
          zu: "Ukhunjulwa njengodadewabo kaHector. Iphuzu likaSipuye ukuthi wayengumbhikishi ngokwakhe, nokuthi isithombe esikhiqizwe kakhulu salolo suku siphethe umkhuba ofanayo wokukhohlwa njengawo wonke umlando.",
          xh: "Ukhunjulwa njengodade boHector. Ingongoma kaSipuye kukuba wayengumqhankqalazi ngokwakhe, nokuba owona mfanekiso uphindaphindwe kakhulu walo mhla uphethe umkhwa ofanayo wokulibala njengayo yonke imbali.",
          st: "O hopolwa e le kgaitsedi wa Hector. Ntlha ya Sipuye ke hore e ne e le moipelaetsi ka boyena, le hore setshwantsho se phatlaladitsweng haholo sa letsatsi leo se jere tlwaelo e tshwanang ya ho lebala jwaloka rekoto kaofela.",
          nso: "O gopolwa bjalo ka kgaetšedi ya Hector. Ntlha ya Sipuye ke gore e be e le mogwanti ka boyena, le gore seswantšho seo se gatišitšwego kudu sa letšatši leo se rwele mokgwa wo o swanago wa go lebala bjalo ka rekhoto ka moka.",
          ss: "Ukhunjulwa njengadzadzewabo waHector. Liphuzu laSipuye kutsi bekangumbhikishi ngekwakhe, nekutsi sitfombe lesikhicitwe kakhulu salelolanga siphetse umkhuba lofanako wekukhohlwa njengemlandvo wonkhe.",
          ts: "U tsundzukiwa tanihi sesi wa Hector. Mhaka ya Sipuye i leswaku a a ri muxikelari hi yexe, ni leswaku xifaniso lexi humesiweke ngopfu xa siku rero xi rhwele mukhuva lowu fanaka wa ku rivala ku fana ni rekhodo hinkwayo.",
          ve: "U humbulwa sa khaladzi wa Hector. Mbuno ya Sipuye ndi ya uri o vha e muhanedzi nga eṋe mune, na uri tshifanyiso tsho gandiswaho nga maanḓa tsha ḓuvha iḽo tsho hwala mukhwa u fanaho wa u hangwa u fana na rekhodo yoṱhe.",
          nr: "Ukhunjulwa njengosesi kaHector. Iphuzu lakaSipuye kukuthi bekamphikisi ngokwakhe, nokuthi isithombe esigadangiswe khulu salelo langa siphethe umkghwa ofanako wokulibala njengomlando woke.",
        },
      },
      "youth-day": {
        kicker: {
          af: "Elke 16 Junie",
          tn: "Ngwaga le ngwaga ka 16 Seetebosigo",
          zu: "Njalo ngomhla ziyi-16 kuJuni",
          xh: "Qho ngomhla we-16 kaJuni",
          st: "Selemo le selemo ka la 16 Phupjane",
          nso: "Ngwaga le ngwaga ka la 16 Juni",
          ss: "Njalo mhla ti-16 Juni",
          ts: "Hi 16 Juni wun'wana ni wun'wana",
          ve: "Nga ḽa 16 Juni ṅwaha muṅwe na muṅwe",
          nr: "Qobe ngomhla ka-16 Juni",
        },
        headline: {
          af: "Jeugdag",
          tn: "Letsatsi la Basha",
          zu: "Usuku Lwentsha",
          xh: "Usuku Lolutsha",
          st: "Letsatsi la Batjha",
          nso: "Letšatši la Baswa",
          ss: "Lilanga Lebasha",
          ts: "Siku ra Vantshwa",
          ve: "Ḓuvha ḽa Vhaswa",
          nr: "Ilanga Lentsha",
        },
        body: {
          af: "Die opstand het oor die land versprei, en ’n geslag jong mense het by die stryd aangesluit. Suid-Afrika gedenk die datum as Jeugdag.",
          tn: "Kgaruru e ne ya anamela mo nageng yotlhe, mme losika lwa basha lwa tsenela ntwa. Aforika Borwa e keteka letlha leo e le Letsatsi la Basha.",
          zu: "Ukuvukela kwasakazeka ezweni lonke, isizukulwane sabantu abasha sajoyina umzabalazo. INingizimu Afrika ikhumbula lolu suku njengoSuku Lwentsha.",
          xh: "Uqhankqalazo lwasasazeka kwilizwe lonke, kwaye isizukulwana sabantu abatsha sazimanya nomzabalazo. UMzantsi Afrika ukhumbula lo mhla njengoSuku Lolutsha.",
          st: "Merusu e ile ya anela naha yohle, mme moloko wa batjha wa kena ntweng. Afrika Borwa e hopola letsatsi lena e le Letsatsi la Batjha.",
          nso: "Tsogelo e phatlaletše naga ka moka, gomme moloko wa baswa wa tsenela ntwa. Afrika-Borwa e gopola letšatši le bjalo ka Letšatši la Baswa.",
          ss: "Kuvukela kwasakateka elive lonkhe, futsi situkulwane sebantfu labasha sajoyina umzabalazo. INingizimu Afrika ikhumbula lelilanga njengeLilanga Lebasha.",
          ts: "Ku pfukela ku hangalakile etikweni hinkwaro, naswona xitukulwana xa vantshwa xi nghene enyimpini. Afrika-Dzonga yi tsundzuka siku leri tanihi Siku ra Vantshwa.",
          ve: "Vhuhanedzi ho phaḓalala shango ḽoṱhe, nahone murafho wa vhaswa wa ṱanganela kha nndwa. Afrika Tshipembe ḽi humbula ḓuvha iḽi sa Ḓuvha ḽa Vhaswa.",
          nr: "Ukuvukela kwarhatjheka enarheni yoke, begodu isizukulwana sabantu abatjha sajoyina ipi yenkululeko. ISewula Afrika ikhumbula ilanga leli njengeLanga Lentsha.",
        },
      },
    },
  },
};
