import React from "react";
import { View, StyleSheet } from "react-native";
import { Lang } from "../content/types";
import { allModules } from "../content";
import { t } from "../i18n";
import { Screen, ScreenHeader, Card, Title, Body, Meta, Muted } from "../ui";
import { spacing } from "../theme/tokens";

// "About the Sources" — credits every author + text, states adaptation vs original, and labels AI
// images as interpretations. Earns Humanities Depth + the "acknowledge sources" ethics rule.
// See docs/04-humanities-sources.md + .claude/skills/humanities-grounding. Built on the UI kit.

const UI = {
  kicker: {
    en: "Acknowledgements", tn: "Ditebogo", af: "Erkennings", zu: "Ukubonga", xh: "Imibulelo",
    nso: "Ditebogo", st: "Liteboho", ss: "Kubonga", ts: "Ku nkhensa", nr: "Ukuthokoza", ve: "Ndilivhuwo",
  },
  title: {
    en: "About the Sources", tn: "Ka ga Metswedi", af: "Oor die bronne", zu: "Mayelana Nemithombo", xh: "Malunga Nemithombo",
    nso: "Ka ga Methopo", st: "Mabapi le Mehlodi", ss: "Mayelana Nemitfombo", ts: "Mayelana ni Tihlovo", nr: "Malunga Nemithombo", ve: "Nga ha Zwiko",
  },
  intro: {
    en: "Ubuntu Heritage is grounded in real, foundational South African texts — not generic summaries. Every story credits its author and source, and we follow one rule: truth only, no invented history.",
    tn: "Ubuntu Heritage e theilwe mo dikwalong tsa nnete tsa motheo tsa Aforika Borwa — e seng dikgutsufatso fela. Kanegelo nngwe le nngwe e tlotla mokwadi le motswedi wa yone, mme re sala morago molao o le mongwe: nnete fela, ga go na hisitori e e itlhametsweng.",
    af: "Ubuntu Heritage is gegrond op werklike, grondliggende Suid-Afrikaanse tekste — nie generiese opsommings nie. Elke storie erken sy skrywer en bron, en ons volg een reël: net die waarheid, geen versinde geskiedenis nie.",
    zu: "I-Ubuntu Heritage isekelwe kwimibhalo yangempela, eyisisekelo yaseNingizimu Afrika — hhayi izifinyezo ezijwayelekile. Zonke izindaba zibonga umbhali nomthombo wazo, futhi silandela umthetho owodwa: iqiniso kuphela, awukho umlando oqanjiwe.",
    xh: "I-Ubuntu Heritage isekwe kwimibhalo yokwenene, esisiseko yaseMzantsi Afrika — hayi izishwankathelo eziqhelekileyo. Onke amabali abulela umbhali nomthombo wawo, kwaye silandela umgaqo omnye: inyaniso kuphela, akukho mbali eqanjiweyo.",
    nso: "Ubuntu Heritage e theilwe godimo ga mengwalo ya nnete, ya motheo ya Afrika Borwa — e sego dikakaretšo tše di tlwaelegilego. Kanegelo e nngwe le e nngwe e leboga mongwadi le mothopo wa yona, gomme re latela molao o tee: therešo fela, ga go na histori ye e itlhametšwego.",
    st: "Ubuntu Heritage e thehiloe hodima mangolo a nnete, a motheo a Afrika Borwa — eseng dikakaretso tse tloaelehileng. Pale e nngwe le e nngwe e leboha mongodi le mohlodi oa eona, mme re latela molao o le mong: nnete feela, ha ho histori e iqapetsoeng.",
    ss: "Ubuntu Heritage isekelwe emibhalweni yangempela, lesisekelo yaseNingizimu Afrika — hhayi tincongophile letejwayelekile. Yonkhe indzaba ibonga umbhali nemtfombo wayo, futsi silandzela umtsetfo munye: liciniso kuphela, akukho mlandvo lowentiwe.",
    ts: "Ubuntu Heritage yi simekiwe eka matsalwa ya ntiyiso, ya masungulo ya Afrika-Dzonga — ku nga ri swikatsakanyo swo tolovela. Ntsheketo wun'wana wu nkhensa mutsari ni xihlovo xa wona, naswona hi landzela nawu wun'we: ntiyiso ntsena, a ku na matimu lama vumbiweke.",
    nr: "Ubuntu Heritage isekelwe eminwalweni yangempela, esisekelo yeSewula Afrika — ingasi iinrhunyeziso ezijayelekileko. Yoke indaba ithokoza umtloli nomthombo wayo, begodu silandela umthetho munye: iqiniso kwaphela, akukho mlando obunjiweko.",
    ve: "Ubuntu Heritage yo thewaho kha maṅwalwa a ngoho, a mutheo a Afrika Tshipembe — hu si khunyeledzo dzo ḓoweleaho. Tshiitwa tshiṅwe na tshiṅwe tshi livhuwa muṅwali na tshiko tshatsho, nahone ri tevhela mulayo muthihi: ngoho fhedzi, a hu na ḓivhazwakale yo vumbiwaho.",
  },
  disclaimer: {
    en: "Scene images are generated by AI as artistic interpretations — they are not historical photographs or depictions of real people.",
    tn: "Ditshwantsho tsa diteng di dirwa ke AI e le dikakanyo tsa botaki — ga se dinepe tsa hisitori kgotsa ditshwantsho tsa batho ba mmatota.",
    af: "Toneelbeelde word deur KI as artistieke interpretasies geskep — dit is nie historiese foto's of uitbeeldings van werklike mense nie.",
    zu: "Izithombe zesigcawu zenziwa yi-AI njengokuhumusha kobuciko — akuzona izithombe zomlando noma ukuvezwa kwabantu bangempela.",
    xh: "Imifanekiso yemiboniso yenziwa yi-AI njengotoliko lobugcisa — asiyoyoyefoto zembali okanye ukubonakaliswa kwabantu bokwenene.",
    nso: "Diswantšho tša seteji di dirwa ke AI bjalo ka ditlhathollo tša bokgabo — ga se dinepe tša histori goba ponagatšo ya batho ba nnete.",
    st: "Ditshwantsho tsa seteji di etsoa ke AI e le ditlhaloso tsa bonono — hase dinepe tsa histori kapa ho hlahisoa ha batho ba nnete.",
    ss: "Titfombe tesigcawu tentiwa yi-AI njengekuhumusha kwebuciko — akusito titfombe temlandvo nome kuvetwa kwebantfu bangempela.",
    ts: "Swifaniso swa xiyimo swi endliwa hi AI tanihi tinhlamuselo ta vutshila — a hi tifoto ta matimu kumbe ku kombisa vanhu va xiviri.",
    nr: "Iinthombe zesigcawu zenziwa yi-AI njengokuhlathulula kobuciko — akusizo iinthombe zomlando namkha ukuvezwa kwabantu bangempela.",
    ve: "Zwifanyiso zwa tshiimo zwi itwa nga AI sa ṱhalutshedzo dza vhutsila — a si zwinepe zwa ḓivhazwakale kana u sumbedza vhathu vha ngoho.",
  },
  rights: {
    en: "Rights", tn: "Ditshwanelo", af: "Regte", zu: "Amalungelo", xh: "Amalungelo",
    nso: "Ditokelo", st: "Ditokelo", ss: "Emalungelo", ts: "Timfanelo", nr: "Amalungelo", ve: "Pfanelo",
  },
  references: {
    en: "References", tn: "Metswedi", af: "Verwysings", zu: "Izinkomba", xh: "Iimbekiselo",
    nso: "Ditšhupetšo", st: "Ditshupiso", ss: "Tinkhomba", ts: "Swikombiso", nr: "Iinkomba", ve: "Zwiredzwa",
  },
};

export function AboutSourcesScreen({ lang, onBack }: { lang: Lang; onBack: () => void }) {
  return (
    <Screen tone="paper">
      <ScreenHeader kicker={t(UI.kicker, lang)} title={t(UI.title, lang)} lang={lang} onBack={onBack} />

      <Body style={styles.intro}>{t(UI.intro, lang)}</Body>

      {allModules.map((m) => (
        <Card key={m.id} style={styles.card}>
          <Title>{m.title}</Title>
          <Meta style={styles.meta}>
            {m.author}
            {m.year ? ` · ${m.year}` : ""}
          </Meta>
          <Muted style={styles.source}>{m.source}</Muted>
          {/* #34 — rights per work, beside the credit, so the About screen never implies the canon is all public domain. */}
          <Muted style={styles.rights}>{t(UI.rights, lang)}: {m.rights.basis}</Muted>
          <Meta style={styles.refLabel}>{t(UI.references, lang)}</Meta>
          {m.references.map((r, i) => (
            <Muted key={i} style={styles.refItem}>
              • {r}
            </Muted>
          ))}
        </Card>
      ))}

      <Card style={styles.disclaimer}>
        <Muted style={styles.disclaimerText}>{t(UI.disclaimer, lang)}</Muted>
      </Card>

      {/* Creator credit — solo entry for the AADHIH "Reclaiming African Voices" hackathon. */}
      <Card style={styles.creator}>
        <Meta style={styles.creatorLabel}>Created by</Meta>
        <Title>Tumo Olorato Mogame</Title>
        <Muted style={styles.creatorNote}>UNISA · AADHIH "Reclaiming African Voices" hackathon</Muted>
      </Card>
    </Screen>
  );
}

const styles = StyleSheet.create({
  intro: { marginBottom: spacing.lg },
  card: { marginBottom: spacing.md },
  meta: { marginTop: 2 },
  source: { fontStyle: "italic", marginTop: spacing.xs },
  rights: { marginTop: spacing.xs, lineHeight: 18 },
  refLabel: { marginTop: spacing.md },
  refItem: { marginTop: 4 },
  disclaimer: { marginTop: spacing.sm },
  disclaimerText: { fontStyle: "italic" },
  creator: { marginTop: spacing.md },
  creatorLabel: { marginBottom: 2 },
  creatorNote: { marginTop: spacing.xs },
});
